### ISSUE TITLE
while using python grammar_check for grammar checking a word document it works perfectly, but when i run for a set of word documents, i get the following error. How to resolve this?  This is the error message:

### ISSUE THREAD

**Issue by sathiyabalu89** [viraja1/grammar-check#4]
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/grammar_check-1.3.1- 
py3.5.egg/grammar_check/__init__.py", line 302, in _get_root
with urlopen(url, data, cls._TIMEOUT) as f:
File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.5/urllib/request.py", line 466, in open
response = self._open(req, data)
File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
'_open', req)
File "/usr/lib/python3.5/urllib/request.py", line 444, in 
_call_chain
result = func(*args)
File "/usr/lib/python3.5/urllib/request.py", line 1282, in 
http_open
return self.do_open(http.client.HTTPConnection, req)
File "/usr/lib/python3.5/urllib/request.py", line 1257, in 
do_open
r = h.getresponse()
File "/usr/lib/python3.5/http/client.py", line 1197, in 
getresponse
response.begin()
File "/usr/lib/python3.5/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/usr/lib/python3.5/http/client.py", line 258, in 
_read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib/python3.5/socket.py", line 575, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by jxmorris12** [comment]
Hi! Since this project has been abandoned, I started a new fork over at https://github.com/jxmorris12/language_tool_python.

My version supports new versions of Java and LanguageTool. language-check is stuck on Java 8 and LanguageTool 3.2; latest versions are Java 14 and LanguageTool 4.9!

I'm happy to help you with your issue if you raise it over at my repository! Thanks!
